spring.application.name=backend
spring.data.mongodb.database=LearnLoop
spring.data.mongodb.uri=mongodb+srv://brainybunch4t:rMHzE2yuL8EiVUUd@lernloop.54uu8fs.mongodb.net/brainybunch4t?retryWrites=true&w=majority&appName=LernLoop
server.port=5000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=./uploads/profile-images
cloudinary.cloud-name=dv6hr5wll
cloudinary.api-key=719886938683934
cloudinary.api-secret=HnnXZxtIml1yN919eOI-xnLrErE