spring.application.name=backend
spring.data.mongodb.database=LearnLoop
spring.data.mongodb.uri=mongodb+srv://brainybunch4t:rMHzE2yuL8EiVUUd@lernloop.54uu8fs.mongodb.net/brainybunch4t?retryWrites=true&w=majority&appName=LernLoop
server.port=5000
file.upload-dir=./uploads/profile-images

cloudinary.cloud-name=dv6hr5wll
cloudinary.api-key=719886938683934
cloudinary.api-secret=HnnXZxtIml1yN919eOI-xnLrErE

# File upload size limit (adjust as needed)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB