spring.application.name=backend
spring.data.mongodb.database=LernLoop
spring.data.mongodb.uri=mongodb+srv://brainybunch4t:rMHzE2yuL8EiVUUd@lernloop.54uu8fs.mongodb.net/LearnLoop?retryWrites=true&w=majority&appName=LearnLoop
server.port=5000